### PR TITLE
only drop all-missing columns, keep columns where some estimate-estim…

### LINKED ISSUE #354: diagnose sticks NA's in if any estimator-estimand pair sends NA's
First design works fine, returns power, then the second design has an additional estimator that doesn't return a p.value and *both* return NA's as diagnosands. Something wrong.

```
> library(DeclareDesign)
> 
> my_custom_estimator <- function(data) return(data.frame(estimate = 5))
> 
> des <- declare_population(N = 100) +
+   declare_potential_outcomes(Y ~ .25 * Z + rnorm(N)) +
+   declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0)) +
+   declare_assignment() +
+   declare_reveal(Y, Z) +
+   declare_estimator(Y ~ Z, estimand = "ATE")
> 
> diagnose_design(des, sims = 50)

Research design diagnosis based on 50 simulations. Diagnosand estimates with bootstrapped standard errors in parentheses (100 replicates).

 Design Label Estimand Label Estimator Label Term N Sims   Bias   RMSE  Power Coverage Mean Estimate SD Estimate Mean Se
          des            ATE       estimator    Z     50   0.00   0.15   0.22     1.00          0.25        0.21    0.20
                                                         (0.02) (0.01) (0.06)   (0.00)        (0.03)      (0.02)  (0.00)
 Type S Rate Mean Estimand
        0.00          0.25
      (0.00)        (0.02)
> 
> des <- des + declare_estimator(handler = tidy_estimator(my_custom_estimator), label = "custom", estimand = "ATE")
> 
> diagnose_design(des, sims = 50)

Research design diagnosis based on 50 simulations. Diagnosand estimates with bootstrapped standard errors in parentheses (100 replicates).

 Design Label Estimand Label Estimator Label N Sims   Bias   RMSE Power Coverage Mean Estimate SD Estimate Mean Se Type S Rate
          des            ATE          custom     50   4.77   4.77    NA       NA          5.00        0.00      NA          NA
                                                    (0.02) (0.02)    NA       NA        (0.00)      (0.00)      NA          NA
          des            ATE       estimator     50   0.00   0.15    NA       NA          0.24        0.17      NA          NA
                                                    (0.02) (0.01)    NA       NA        (0.02)      (0.02)      NA          NA
 Mean Estimand
          0.23
        (0.02)
          0.23
        (0.02)
```

Also this is odd:

```
> diagnose_design(des, sims = 50, diagnosands = declare_diagnosands(select = power))
Error in mean(p.value < alpha) : object 'p.value' not found
```

### PR DESCRIPTION
**Pull request by graemeblair**
…and pairs have values

closes https://github.com/DeclareDesign/DeclareDesign/issues/354

### CODE REVIEW

File: R/simulate_design.R [hunk 1]
```diff
@@ -164,7 +164,7 @@ simulate_single_design <- function(design, sims) {
     estimates_df_split <- split(x = estimates_df, f = estimates_df$estimand_label)
     
     non_missing_columns <- function(dat){
-      nonmissing <- apply(dat, 2, FUN = function(x) all(!is.na(x)))
+      nonmissing <- apply(dat, 2, FUN = function(x) any(!is.na(x)))
```
Comment (nfultz) [inline R/simulate_design.R:167]: use vapply for predicates -

**Review by nfultz — APPROVED** [review]
lgtm
