### PR TITLE
deal with NAs in group_by_set

### LINKED ISSUE #301: disappearing diagnosis
I have a design that produces the following simulations df using simulate_design 

```
> sims_df
  design_label sim_ID estimand_label    estimand estimator_label         est coefficient        se         p   ci_lower  ci_upper
1       design      1        control -0.06675827              A1 -0.06334958        <NA>        NA        NA         NA        NA
2       design      1            ate  0.17865929              A2  0.13914128           Z 0.2603802 0.5944165 -0.3782478 0.6565304
> diagnose_design(sims_df)
```

Note the <.NA.> for coefficient for A1. ( A1 uses a custom function and A2 uses Y~Z.)

There should be two rows to the diagnosis, but there is only 1:

```
Research design diagnosis based on 1 simulations. Diagnosand estimates with bootstrapped standard errors in parentheses (100 replicates).

 Design Label Estimand Label Estimator Label Coefficient N Sims   Bias   RMSE  Power Coverage Mean Estimate SD Estimate Mean Se
       design            ate              A2           Z      1  -0.04   0.04   0.00     1.00          0.14          NA    0.26
                                                                (0.00) (0.00) (0.00)   (0.00)        (0.00)          NA  (0.00)

```

If I remove the <.NA.> it will work alright.

What is better behavior? Treat NA as a value when creating sets for diagnosis?

### LINKED ISSUE #304: term
I think we have problems with the current "term" approach for estimates taken from a model

 * First the estimands get odd names (`(Intercept)`) 
 * Second the estimands are  a pain to name  as you need to consult with model output; and the names are and not in the spirit of estimands based on potential outcomes
 * Third it seems to run into issues when combined with other appraoches as shown below
 * Fourth we don't need it. We are already able to do the same thing in a simpler way, see below

Is there anything against the simpler approach below?

```
# The issue:

population  <- declare_population(N = 100, X = rnorm(N))
potentials  <- declare_potential_outcomes(Y ~ (.25 + X) * Z + rnorm(N))
assignment  <- declare_assignment(m = 50)
design_stub <- population +  potentials + assignment + declare_reveal()

estimands_regression <- declare_estimand(
  `(Intercept)` = mean(Y_Z_0),
  `Z` = mean(Y_Z_1 - Y_Z_0),
  term = TRUE,
  label="Regression_Estimands")

estimators_regression <- declare_estimator(
  Y ~ Z,
  estimand = estimands_regression,
  model = lm,
  term = TRUE
)

estimand_2  <- declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0),   label = "ate_simple")
estimator_2 <- declare_estimator(Y~Z, estimand = estimand_2, label = "dim")

design <- design_stub + estimands_regression + estimators_regression  + estimand_2 + estimator_2

# This has four rows instead of 3
simulate_design(design, sims = 1)

# This produces a warning and fails to connect estimates to estimand for dim
diagnose_design(design, sims = 2)

# Note that constituent parts work ok when declared separately
design_A <- design_stub + estimand_2 + estimator_2
diagnose_design(design_A, sims = 2)

design_B <- design_stub + estimands_regression + estimators_regression
diagnose_design(design_B, sims = 2)
```

# A simpler, better approach?

* Getting rid of term from the estimands declaration seems a lot simpler and gives users control over names
* Then in estimates declaration give the estimands of interest. "term" is a bit of a funny term for term. 
* With this usage, the older term "coefficients"  seems more accurate

```

estimands_regression <- declare_estimand(
  Q1 = mean(Y_Z_0),
  Q2 = mean(Y_Z_1 - Y_Z_0),
  label="Regression_Estimands")

estimators_regression <- declare_estimator(
  Y ~ Z,
  estimand = c("Q1", "Q2"),
  model = lm,
  term = TRUE
)

design <- design_stub + estimands_regression + estimators_regression + estimand_2 + estimator_2

# Now fine
simulate_design(design, sims = 1)

# Now fine
diagnose_design(design, sims = 2)

# To boot: nice flexibility to access different estimands 
estimator_3 <- declare_estimator(Y~Z, estimand = c(estimand_2, "Q2"), label = "dim2")
diagnose_design(design + estimator_3,  sims = 20)
```

### PR DESCRIPTION
**Pull request by acoppock**
This closes #304.

Edit: also closes https://github.com/DeclareDesign/DeclareDesign/issues/301

I'm getting an error in the tests saying that DesignLibrary can't find DeclareDesign, which I don't understand.

This also fixes a weird thing that if you have an estimand that has not estimators, it used to not be in the dx output, but now it is.

This approach might have unintended consequences, but I don't intend them.

### CODE REVIEW

File: tests/testthat/test-diagnose-design.R [hunk 1]
```diff
@@ -198,3 +198,15 @@ test_that("default diagnosands work", {
   diag <- diagnose_design(sims, sims = 5, bootstrap_sims = FALSE)
 })
 
+
+test_that("with and without term",{
+  library(DeclareDesign)
+  library(DesignLibrary)
```
Comment (nfultz) [inline tests/testthat/test-diagnose-design.R]: Generally we don't want library inside a test, use the skip_if_not_installed to check, and then do DesignLibrary::simple_factorial_designer.

File: R/diagnose_design.R [hunk 2]
```diff
@@ -220,6 +220,7 @@ calculate_diagnosands <- function(simulations_df, diagnosands, group_by_set) {
 
 calculate_diagnosands_single_design <- function(simulations_df, diagnosands, group_by_set) {
   group_by_list <- simulations_df[, group_by_set, drop = FALSE]
+  group_by_list[is.na(group_by_list)] <- "NA"
```
Comment (nfultz) [inline R/diagnose_design.R]: Are we sure that we aren't accidentally changing numbers into text bc of this?

Comment (nfultz) [reply R/diagnose_design.R]: For pretty printing you might want `""` instead of `"NA"`.

**Review by nfultz — DISMISSED** [review]

File: tests/testthat/test-diagnose-design.R (hunk 1 above)
Comment (acoppock) [reply tests/testthat/test-diagnose-design.R]: great, thank you

File: R/diagnose_design.R (hunk 2 above)
Comment (acoppock) [reply R/diagnose_design.R]: ooh, i'll check about numbers and text

Comment (macartan) [reply R/diagnose_design.R]: add_grouping_variables could contain columns with numbers.

File: tests/testthat/test-diagnose-design.R (hunk 1 above)
Comment (acoppock) [reply tests/testthat/test-diagnose-design.R]: done

**Comment by acoppock** [comment]
it turns out that this:

`split(group_by_list, lapply(group_by_list, addNA), drop = TRUE)`

solves the problem without messing wtih types or dropping columns.

**Review by nfultz — APPROVED** [review]
lgtm
