### PR TITLE
bootstrap fixes

### LINKED ISSUE #261: bootstrap at highest level
check the fans

### LINKED ISSUE #273: set_diagnosands
Aims: 
- enable `diagnose_design(my_designer())` to work even when default diagnosands won't, so setting diagnosands specific to the designer; and 
- make it easy for users to tell us what diagnosands are important for their design.

@macartan proposal:

1. set_diagnosands to add attribute 

2.  Diagnose design -- if no diagnosand stipulated, default is
A. Look for diagnosand attributes
B. If not, try default diagnosands

Need a default for diagnose_design also when diagnosands are not set for a design.

### LINKED ISSUE #279: reshape_diagnosis is putting SEs at the bottom now
When using multiple designs or estimators I'm getting all the bootstrap SEs at the bottom of the table. I notice many of the vignettes have this atm too. 
[For example.](https://declaredesign.org/library/articles/cluster_sampling.html)
 
MWE

```r
population <- declare_population(N = 10, x = rnorm(N),y = rnorm(N))
estimand <- declare_estimand(cov = 0)
estimator_1 <- declare_estimator(y ~ x,coefficients = x,model = lm_robust,estimand = estimand,label = "est_1")
estimator_2 <- declare_estimator(y ~ x,coefficients = x,model = lm_robust,estimand = estimand,label = "est_2")
design_1 <- population + estimator_1 + estimand
design_2 <- population + estimator_2 + estimand
design_3 <- population + estimator_1 + estimator_2 + estimand

diagnose_design(design_1,design_2)
diagnose_design(design_3)

```
Gives

```
Design Label Estimand Label Estimator Label Coefficient N Sims   Bias   RMSE  Power Coverage
     design_1            cov           est_1           x    500  -0.01   0.40   0.10     0.90
     design_2            cov           est_2           x    500   0.02   0.35   0.06     0.94
                                                                (0.02) (0.02) (0.01)   (0.01)
                                                                (0.02) (0.01) (0.01)   (0.01)
```

and

```
Design Label Estimand Label Estimator Label Coefficient N Sims   Bias   RMSE  Power Coverage
     design_3            cov           est_1           x    500   0.00   0.38   0.10     0.90
     design_3            cov           est_2           x    500   0.00   0.38   0.10     0.90
                                                                (0.02) (0.01) (0.01)   (0.01)
                                                                (0.02) (0.01) (0.01)   (0.01)
```

### PR DESCRIPTION
**Pull request by graemeblair**
changes so that we always bootstrap at the top of the fan-out strategy (if there is one)
adds support for set_diagnosis

closes #261
closes #279
closes #273

### CODE REVIEW

File: R/simulate_design.R [hunk 1]
```diff
@@ -69,7 +69,7 @@ simulate_design <- function(..., sims = 500) {
     # if you provide a list of sims for each design, i.e.
     #   sims = list(my_design_1 = c(100, 1, 1), my_design_2 = 200)
     # use it! otherwise, create a list of length designs that repeats the sims
-    if (!is_list(sims)) {
+    if (!inherits(sims, "list")) {
```
Comment (nfultz) [inline R/simulate_design.R]: be careful here, seems potentially edgy

File: R/diagnose_design.R [hunk 2]
```diff
@@ -220,8 +220,10 @@ calculate_sims <- function(simulations_df, group_by_set) {
 
 bootstrap_diagnosands <- function(bootstrap_sims, simulations_df, diagnosands, diagnosands_df, group_by_set) {
   
-  boot_indicies_by_id <- split(seq_len(nrow(simulations_df)), simulations_df$sim_ID)
-  nsims <- max(simulations_df$sim_ID)
+  bootstrap_level <- ifelse("fan_1" %in% names(simulations_df), "fan_1", "sim_ID")
```
Comment (nfultz) [inline R/diagnose_design.R]: constant from no where.

File: tests/testthat/test-fanout.R [hunk 3]
```diff
@@ -83,17 +83,17 @@ test_that("sims expansion is correct",{
...
+#     declare_estimand(b = rnorm(1))
+#   
+#   fan <- data.frame(end = 1:3, n = c(5, 5, 5))
+# 
+#   fo <- diagnose_design(design, sims = fan)
+# 
+#   fo_id <- fo$simulations[paste0("fan_", 1:3)]
+# 
+#   expect_equal(nrow(unique(fo_id)), prod(fan$n))
+# })
```
Comment (nfultz) [inline tests/testthat/test-fanout.R]: :(

File: tests/testthat/test-fanout.R [hunk 4]
```diff
@@ -5,7 +5,7 @@ test_that("Fanout does something",{
   N <- 100
 
   pop <- declare_population(N = N)
-  pop2 <- declare_population(noise = rnorm(N))
+  pop2 <- declare_step(fabricate, noise = rnorm(N))
```
Comment (nfultz) [inline tests/testthat/test-fanout.R:8]: for why? multiple declare_pop is allowed.

**Review by nfultz — COMMENTED** [review]
can you add a test for the bad behavior you are trying to fix - not obvious just from changes.

**Comment by nfultz** [comment]
See also #270

File: R/simulate_design.R (hunk 1 above)
Comment (macartan) [reply R/simulate_design.R]: This scares me also; why not just do the diagnosis separately...
```
 # if you provide a list of sims for each design, i.e.
 #   sims = list(my_design_1 = c(100, 1, 1), my_design_2 = 200)
# use it! otherwise, create a list of length designs that repeats the sims
```

Comment (macartan) [reply R/simulate_design.R]: Regarding tests. The kind of problem we have if we takes simulations from other levels arises in situations like the below. 

We get very different answers every time but with a lot of misplaced confidence in the answers because the draws below the top level are not independent. 

In  a case like the below if we used the top level we should really warn people that the bootstrapping is based on draws from a single simulation!

I suggest a warning of that form f the top level is <100, say

```
library(DeclareDesign)
U <- declare_population(
  world = add_level(N = 1, tau = sample(0:1,1)),
  samp  = add_level(N = 10, Y_Z_0 = rnorm(N)/100, Y_Z_1 = 1)
)

Z <- declare_assignment()

R <- declare_reveal()

Q <- declare_estimand(inq = mean(tau))

A <- declare_estimator(Y~Z, estimand = "inq")


des <- U + Z + R + Q + A 

set.seed(1)
diagnose_design(des,  sims = c(1, 100, 1, 1, 1))

set.seed(2)
diagnose_design(des,  sims = c(1, 100, 1, 1, 1))
```
