### PR TITLE
fix bootstrapping bug

### LINKED ISSUE #311: bootstrapping bug
Noticed that this:

```
d <- simple_two_arm_designer()

diagnose_design(d, sims = c(5, 1, 1, 1, 1, 1), diagnosands = declare_diagnosands(select = "mean_estimate"))

 Design Label Estimand Label Estimator Label Term N Sims Mean Estimate
            d            ATE       estimator    Z      5          0.92
                                                                (0.00)
```

has no variance, but it should.

Issue seems to be with fan:
```
> s <- simulate_design(d, sims = c(5, 1, 1, 1, 1, 1))
> s
        df outcome fan_1 fan_2
1 96.92058       Y     1     1
2 95.01188       Y     1     2
3 97.38123       Y     1     3
4 97.99933       Y     1     4
5 93.14810       Y     1     5
```

This should have fan_1 running from 1 to 5 and fan_2 at 1, surely?
Looks like fans are being numbered backwards.

It's treating this as having a single top level fan. 

```
> bootstrap_level <- if ("fan_1" %in% names(simulations_df)) "fan_1" else "sim_ID"
> 
>   boot_indicies_by_id <- split(seq_len(nrow(simulations_df)), simulations_df[, bootstrap_level])
>   nsims <- max(simulations_df[, bootstrap_level])
> nsims
[1] 1
```
It then "samples" all the cases that have fan_1 = 1 and calculates the diagnosands on these. So no variation.

**We need some tests to make sure bootstrapping is performing correctly. eg coverage tests perhaps?**

### PR DESCRIPTION
**Pull request by graemeblair**
closes https://github.com/DeclareDesign/DeclareDesign/issues/311

### CODE REVIEW

**Comment by nfultz** [comment]
This still doesn't look quite right.

File: R/simulate_design.R [hunk 1]
```diff
@@ -122,9 +122,9 @@ simulate_single_design <- function(design, sims) {
     results_list <- fan_out(design, sims)
     fan_id <- setNames(
       lapply(rev(sims$n), seq),
-      paste0("fan_", seq_len(nrow(sims)))
+      paste0("fan_", rev(seq_len(nrow(sims))))
     )
-    fan_id <- expand.grid(fan_id)
+    fan_id <- expand.grid(rev(fan_id))
```
Comment (nfultz) [inline R/simulate_design.R]: I see this:

```
> sims <- data.frame(end=1:3, n=c(1,5,2))
>     fan_id <- setNames(
+       lapply(rev(sims$n), seq),
+       paste0("fan_", rev(seq_len(nrow(sims))))
+     )
>     fan_id <- expand.grid(rev(fan_id))
> fan_id
   fan_1 fan_2 fan_3
1      1     1     1
2      1     2     1
3      1     3     1
4      1     4     1
5      1     5     1
6      1     1     2
7      1     2     2
8      1     3     2
9      1     4     2
10     1     5     2
> 
```



Should verify this, it needs to match fan_out() exactly.

File: tests/testthat/test-simulate-design.R [hunk 2]
```diff
@@ -75,3 +75,15 @@ test_that("no estimates estimands declared", {
...
+
+
+test_that("fan out IDs are correct", {
+  
+  skip_if_not_installed("DesignLibrary")
+  
+  sims <- c(3, 1, 2, 1, 1, 2)
+  design <- DesignLibrary::simple_two_arm_designer(rho = 0)
+  
+  simulate_design(design, sims = sims)[, c(4, 7, 15:19)]
```
Comment (nfultz) [inline tests/testthat/test-simulate-design.R]: this needs an expect_something somewhere, ow testthat might skip it.

**Comment by nfultz** [comment]
Here is a design that could actually test that this is being set correctly:

```
> f1 <- local({i <- 0; function(){i<<- i+1; i} })
> f2 <- local({i <- 0; function(){i<<- i+1; i} })
> f3 <- local({i <- 0; function(){i<<- i+1; i} })
> e1 <- declare_estimand(a=f1())
> e2 <- declare_estimand(b=f2())
> e3 <- declare_estimand(c=f3())
> out <- simulate_design(declare_population(sleep) + e1 + e2 + e3, sims=c(1,1,5,2))
Warning message:
We recommend you choose a higher number of simulations than 1 for the top level of simulation.
> out
   design_label sim_ID estimand_label estimand fan_1 fan_2 fan_3
1      design_1      1              a        1     1     1     1
2      design_1      1              b        1     1     1     1
3      design_1      1              c        1     1     1     1
4      design_1      2              a        1     2     1     1
5      design_1      2              b        1     2     1     1
6      design_1      2              c        2     2     1     1
7      design_1      3              a        1     1     2     1
8      design_1      3              b        2     1     2     1
9      design_1      3              c        3     1     2     1
10     design_1      4              a        1     2     2     1
11     design_1      4              b        2     2     2     1
12     design_1      4              c        4     2     2     1
13     design_1      5              a        1     1     3     1
14     design_1      5              b        3     1     3     1
15     design_1      5              c        5     1     3     1
16     design_1      6              a        1     2     3     1
17     design_1      6              b        3     2     3     1
18     design_1      6              c        6     2     3     1
19     design_1      7              a        1     1     4     1
20     design_1      7              b        4     1     4     1
21     design_1      7              c        7     1     4     1
22     design_1      8              a        1     2     4     1
23     design_1      8              b        4     2     4     1
24     design_1      8              c        8     2     4     1
25     design_1      9              a        1     1     5     1
26     design_1      9              b        5     1     5     1
27     design_1      9              c        9     1     5     1
28     design_1     10              a        1     2     5     1
29     design_1     10              b        5     2     5     1
30     design_1     10              c       10     2     5     1
> dcast(out, design_label+fan_1+fan_2+fan_3~estimand_label, value.var="estimand")
   design_label fan_1 fan_2 fan_3 a b  c
1      design_1     1     1     1 1 1  1
2      design_1     1     2     1 1 2  3
3      design_1     1     3     1 1 3  5
4      design_1     1     4     1 1 4  7
5      design_1     1     5     1 1 5  9
6      design_1     2     1     1 1 1  2
7      design_1     2     2     1 1 2  4
8      design_1     2     3     1 1 3  6
9      design_1     2     4     1 1 4  8
10     design_1     2     5     1 1 5 10
```

File: tests/testthat/test-simulate-design.R (hunk 2 above)
Comment (acoppock) [reply tests/testthat/test-simulate-design.R]: done, thx

File: R/simulate_design.R (hunk 1 above)
Comment (acoppock) [reply R/simulate_design.R]: can you say more? I don't know what you mean.

Comment (nfultz) [reply R/simulate_design.R]: Shouldn't fan_3 be 1:10 (since each of them is a different execution)? Having it only 1,2 makes it look like it was only run twice.  See the example design I posted on the PR.

Comment (nfultz) [reply R/simulate_design.R]: Eg grouping by fan_3 would give you nonsense numbers I think.

Comment (nfultz) [reply R/simulate_design.R]: How about this:

```
> s <- setNames(sims$n, paste0("step_", seq(nrow(sims))))
> do.call(cbind.data.frame, lapply(cumprod(s), seq_len))
step_1 step_2 step_3
1       1      1      1
2       1      2      2
3       1      3      3
4       1      4      4
5       1      5      5
6       1      1      6
7       1      2      7
8       1      3      8
9       1      4      9
10      1      5     10
```

Comment (acoppock) [reply R/simulate_design.R]: Sorry, I really don't understand.  if you were to group by step 2 in the example above, wouldn't it also give you nonsense?  i.e., the "1" group in step_2 refers to two independent draws, no?

Comment (nfultz) [reply R/simulate_design.R]: No, it's the same draw - estimand b in the design I posted was exactly the same.

Comment (nfultz) [reply R/simulate_design.R]: Here is a somewhat more explicit example where you can see how the random draws propogate:

```
> require(DeclareDesign)
> require(reshape2)
> 
> f1 <- local({i <- 0; function(){i<<- i+1; i} })
> f2 <- local({i <- 0; function(){i<<- i+1; i} })
> f3 <- local({i <- 0; function(){i<<- i+1; i} })
> 
> e1 <- declare_estimand(a=f1(), ar=rnorm(1), term=TRUE, label='e1')
> e2 <- declare_estimand(b=f2(), br=rnorm(1), term=TRUE, label='e2')
> e3 <- declare_estimand(c=f3(), cr=rnorm(1), term=TRUE, label='e3')
> out <- simulate_design(declare_population(sleep) + e1 + e2 + e3, sims=c(1,1,5,2))
Warning message:
We recommend you choose a higher number of simulations than 1 for the top level of simulation. 
> 
> dcast(out, design_label+fan_1+fan_2+fan_3~estimand_label+term, value.var="estimand")
   design_label fan_1 fan_2 fan_3 e1_a       e1_ar e2_b         e2_br e3_c         e3_cr
1      design_1     1     1     1    1 1.516604121    1 -1.3027235383    1  0.3052041011
2      design_1     1     2     1    1 1.516604121    2 -0.2363384340    3 -0.4535625357
3      design_1     1     3     1    1 1.516604121    3 -0.1916714742    5  1.5182842803
4      design_1     1     4     1    1 1.516604121    4 -0.9283954334    7 -0.9957436604
5      design_1     1     5     1    1 1.516604121    5  0.2547567283    9  0.1836362585
6      design_1     2     1     1    1 1.516604121    1 -1.3027235383    2  0.8118381599
7      design_1     2     2     1    1 1.516604121    2 -0.2363384340    4 -0.5319524033
8      design_1     2     3     1    1 1.516604121    3 -0.1916714742    6 -2.4692229482
9      design_1     2     4     1    1 1.516604121    4 -0.9283954334    8 -0.6679191953
10     design_1     2     5     1    1 1.516604121    5  0.2547567283   10 -1.0457122748
```

Comment (acoppock) [reply R/simulate_design.R]: thanks very much for the help, I think I have it now in the latest commit.

**Comment by acoppock** [comment]
sim_ID is the name of the column if no fans are used, so I think it's a good thing to leave in there!  but I agree it will be the same as the final column.  I've got no problem with the redundancy.

**Comment by nfultz** [comment]
In that case, would recommend setting `fan_ID$sim_ID <- fan_ID[[ncol(fan_ID)]]` to enforce they are the same and minor performance/memory benefit should anyone run a million simulations.

**Comment by acoppock** [comment]
done -- thanks!
