### PR TITLE
fixes missing params issue

### LINKED ISSUE #225: disappearing parameters
```
N = 5
e = 1
U <- declare_population(N = 5, X = e)
design <- U + NULL
design2 <- redesign(design, N = 1, e = 0)
attributes(design2)

> attributes(design2)
$call
construct_design(!!!qs)

$class
[1] "design" "dd"    

$names
[1] "U"

$parameters
  N
1 1
```

### PR DESCRIPTION
**Pull request by graemeblair**
closes https://github.com/DeclareDesign/DeclareDesign/issues/225

### CODE REVIEW

File: R/expand_design_redesign.R [hunk 1]
```diff
@@ -36,7 +37,7 @@
 #' }
 #'
 #' @export
-expand_design <- function(template, ..., expand = TRUE, prefix = "design") {
+expand_design <- function(designer, expand = TRUE, prefix = "design", ...) {
```
Comment (nfultz) [inline R/expand_design_redesign.R]: you moved the dots back?

Comment (graemeblair) [reply R/expand_design_redesign.R]: thx - damnit, my fault, this was merging in changes from master. will fix.

**Comment by graemeblair** [comment]
I think this is good to go, @nfultz?
